// 简单的英文到中文翻译字典（常见词汇）
const translationDict: { [key: string]: string } = {
  // 通用词汇
  'ai': 'AI',
  'artificial intelligence': '人工智能',
  'machine learning': '机器学习',
  'deep learning': '深度学习',
  'neural network': '神经网络',
  'algorithm': '算法',
  'model': '模型',
  'data': '数据',
  'training': '训练',
  'prediction': '预测',
  'analysis': '分析',
  'technology': '技术',
  'innovation': '创新',
  'startup': '初创公司',
  'company': '公司',
  'business': '业务',
  'market': '市场',
  'investment': '投资',
  'funding': '融资',
  'product': '产品',
  'service': '服务',
  'platform': '平台',
  'application': '应用',
  'system': '系统',
  'software': '软件',
  'hardware': '硬件',
  'cloud': '云',
  'security': '安全',
  'privacy': '隐私',
  'user': '用户',
  'developer': '开发者',
  'engineer': '工程师',
  'research': '研究',
  'development': '开发',
  'feature': '功能',
  'update': '更新',
  'release': '发布',
  'version': '版本',
  'performance': '性能',
  'optimization': '优化',
  'improvement': '改进',
  'challenge': '挑战',
  'solution': '解决方案',
  'problem': '问题',
  'issue': '问题',
  'bug': '漏洞',
  'fix': '修复',
  'error': '错误',
  'warning': '警告',
  'success': '成功',
  'failure': '失败',
  'test': '测试',
  'quality': '质量',
  'standard': '标准',
  'framework': '框架',
  'library': '库',
  'tool': '工具',
  'language': '语言',
  'code': '代码',
  'programming': '编程',
  'script': '脚本',
  'database': '数据库',
  'server': '服务器',
  'client': '客户端',
  'network': '网络',
  'internet': '互联网',
  'web': '网络',
  'mobile': '移动',
  'desktop': '桌面',
  'app': '应用',
  'website': '网站',
  'browser': '浏览器',
  'api': 'API',
  'interface': '界面',
  'design': '设计',
  'ui': 'UI',
  'ux': 'UX',
  'experience': '体验',
  'user experience': '用户体验',
  'interface design': '界面设计',
  'graphic': '图形',
  'animation': '动画',
  'video': '视频',
  'audio': '音频',
  'image': '图像',
  'media': '媒体',
  'content': '内容',
  'text': '文本',
  'document': '文档',
  'file': '文件',
  'folder': '文件夹',
  'directory': '目录',
  'storage': '存储',
  'memory': '内存',
  'processor': '处理器',
  'cpu': 'CPU',
  'gpu': 'GPU',
  'ram': 'RAM',
  'ssd': 'SSD',
  'hdd': 'HDD',
  'battery': '电池',
  'power': '电源',
  'energy': '能量',
  'speed': '速度',
  'fast': '快速',
  'slow': '缓慢',
  'efficient': '高效',
  'reliable': '可靠',
  'stable': '稳定',
  'robust': '强大',
  'flexible': '灵活',
  'scalable': '可扩展',
  'modular': '模块化',
  'open source': '开源',
  'closed source': '闭源',
  'free': '免费',
  'paid': '付费',
  'license': '许可证',
  'copyright': '版权',
  'patent': '专利',
  'trademark': '商标',
  'legal': '法律',
  'compliance': '合规',
  'regulation': '规定',
  'policy': '政策',
  'agreement': '协议',
  'contract': '合同',
  'terms': '条款',
  'condition': '条件',
  'requirement': '要求',
  'specification': '规范',
  'documentation': '文档',
  'manual': '手册',
  'guide': '指南',
  'tutorial': '教程',
  'example': '示例',
  'demo': '演示',
  'sample': '样本',
  'template': '模板',
  'preset': '预设',
  'configuration': '配置',
  'setting': '设置',
  'option': '选项',
  'parameter': '参数',
  'argument': '参数',
  'variable': '变量',
  'constant': '常数',
  'function': '函数',
  'method': '方法',
  'class': '类',
  'object': '对象',
  'array': '数组',
  'list': '列表',
  'map': '映射',
  'dictionary': '字典',
  'set': '集合',
  'queue': '队列',
  'stack': '栈',
  'tree': '树',
  'graph': '图',
  'node': '节点',
  'edge': '边',
  'path': '路径',
  'route': '路由',
  'connection': '连接',
  'link': '链接',
  'reference': '引用',
  'pointer': '指针',
  'memory address': '内存地址',
  'garbage collection': '垃圾回收',
  'memory leak': '内存泄漏',
  'buffer overflow': '缓冲区溢出',
  'stack overflow': '栈溢出',
  'deadlock': '死锁',
  'race condition': '竞态条件',
  'thread': '线程',
  'process': '进程',
  'task': '任务',
  'job': '作业',
  'queue': '队列',
  'scheduler': '调度器',
  'dispatcher': '分发器',
  'handler': '处理器',
  'listener': '监听器',
  'observer': '观察者',
  'event': '事件',
  'callback': '回调',
  'promise': '承诺',
  'async': '异步',
  'await': '等待',
  'synchronous': '同步',
  'asynchronous': '异步',
  'concurrent': '并发',
  'parallel': '并行',
  'distributed': '分布式',
  'decentralized': '去中心化',
  'centralized': '集中式',
  'peer to peer': '点对点',
  'client server': '客户端服务器',
  'microservice': '微服务',
  'monolithic': '单体',
  'architecture': '架构',
  'design pattern': '设计模式',
  'best practice': '最佳实践',
  'convention': '约定',
  'standard': '标准',
  'protocol': '协议',
  'http': 'HTTP',
  'https': 'HTTPS',
  'ftp': 'FTP',
  'ssh': 'SSH',
  'ssl': 'SSL',
  'tls': 'TLS',
  'encryption': '加密',
  'decryption': '解密',
  'hash': '哈希',
  'checksum': '校验和',
  'signature': '签名',
  'certificate': '证书',
  'authentication': '认证',
  'authorization': '授权',
  'permission': '权限',
  'role': '角色',
  'access control': '访问控制',
  'firewall': '防火墙',
  'proxy': '代理',
  'vpn': 'VPN',
  'tor': 'Tor',
  'blockchain': '区块链',
  'cryptocurrency': '加密货币',
  'bitcoin': '比特币',
  'ethereum': '以太坊',
  'smart contract': '智能合约',
  'token': '代币',
  'nft': 'NFT',
  'defi': 'DeFi',
  'web3': 'Web3',
  'metaverse': '元宇宙',
  'virtual reality': '虚拟现实',
  'augmented reality': '增强现实',
  'mixed reality': '混合现实',
  'extended reality': '扩展现实',
  'iot': 'IoT',
  'internet of things': '物联网',
  'sensor': '传感器',
  'actuator': '执行器',
  'robot': '机器人',
  'automation': '自动化',
  'robotics': '机器人技术',
  'drone': '无人机',
  'autonomous': '自主',
  'self driving': '自动驾驶',
  'vehicle': '车辆',
  'car': '汽车',
  'truck': '卡车',
  'bus': '公交车',
  'train': '火车',
  'plane': '飞机',
  'helicopter': '直升机',
  'ship': '船',
  'boat': '小船',
  'transportation': '运输',
  'logistics': '物流',
  'supply chain': '供应链',
  'inventory': '库存',
  'warehouse': '仓库',
  'distribution': '分发',
  'delivery': '交付',
  'shipping': '运输',
  'tracking': '追踪',
  'gps': 'GPS',
  'location': '位置',
  'map': '地图',
  'navigation': '导航',
  'direction': '方向',
  'distance': '距离',
  'time': '时间',
  'date': '日期',
  'calendar': '日历',
  'schedule': '日程',
  'appointment': '约会',
  'meeting': '会议',
  'conference': '会议',
  'presentation': '演示',
  'speech': '演讲',
  'lecture': '讲座',
  'seminar': '研讨会',
  'workshop': '工作坊',
  'training': '培训',
  'course': '课程',
  'class': '课程',
  'lesson': '课程',
  'education': '教育',
  'learning': '学习',
  'teaching': '教学',
  'student': '学生',
  'teacher': '教师',
  'professor': '教授',
  'instructor': '讲师',
  'mentor': '导师',
  'coach': '教练',
  'school': '学校',
  'university': '大学',
  'college': '学院',
  'academy': '学院',
  'institute': '研究所',
  'library': '图书馆',
  'book': '书',
  'magazine': '杂志',
  'newspaper': '报纸',
  'journal': '期刊',
  'article': '文章',
  'paper': '论文',
  'thesis': '论文',
  'dissertation': '论文',
  'research paper': '研究论文',
  'publication': '出版物',
  'publisher': '出版商',
  'author': '作者',
  'writer': '作家',
  'editor': '编辑',
  'reviewer': '审稿人',
  'peer review': '同行评审',
  'citation': '引用',
  'reference': '参考',
  'bibliography': '参考文献',
  'index': '索引',
  'table of contents': '目录',
  'chapter': '章节',
  'section': '部分',
  'paragraph': '段落',
  'sentence': '句子',
  'word': '单词',
  'phrase': '短语',
  'idiom': '习语',
  'slang': '俚语',
  'dialect': '方言',
  'accent': '口音',
  'pronunciation': '发音',
  'grammar': '语法',
  'syntax': '语法',
  'semantics': '语义',
  'vocabulary': '词汇',
  'dictionary': '字典',
  'thesaurus': '同义词库',
  'translation': '翻译',
  'interpreter': '翻译',
  'translator': '翻译',
  'language': '语言',
  'english': '英语',
  'chinese': '中文',
  'spanish': '西班牙语',
  'french': '法语',
  'german': '德语',
  'japanese': '日语',
  'korean': '韩语',
  'russian': '俄语',
  'arabic': '阿拉伯语',
  'hindi': '印地语',
  'portuguese': '葡萄牙语',
  'italian': '意大利语',
  'dutch': '荷兰语',
  'swedish': '瑞典语',
  'norwegian': '挪威语',
  'danish': '丹麦语',
  'finnish': '芬兰语',
  'polish': '波兰语',
  'czech': '捷克语',
  'hungarian': '匈牙利语',
  'romanian': '罗马尼亚语',
  'greek': '希腊语',
  'turkish': '土耳其语',
  'thai': '泰语',
  'vietnamese': '越南语',
  'indonesian': '印度尼西亚语',
  'malay': '马来语',
  'tagalog': '他加禄语',
  'burmese': '缅甸语',
  'khmer': '高棉语',
  'lao': '老挝语',
  'cambodian': '柬埔寨语',
  'hebrew': '希伯来语',
  'persian': '波斯语',
  'urdu': '乌尔都语',
  'bengali': '孟加拉语',
  'tamil': '泰米尔语',
  'telugu': '泰卢固语',
  'kannada': '卡纳达语',
  'malayalam': '马拉雅拉姆语',
  'marathi': '马拉地语',
  'gujarati': '古吉拉特语',
  'punjabi': '旁遮普语',
  'sikh': '锡克语',
  'afrikaans': '南非荷兰语',
  'irish': '爱尔兰语',
  'scottish': '苏格兰语',
  'welsh': '威尔士语',
  'basque': '巴斯克语',
  'catalan': '加泰罗尼亚语',
  'galician': '加利西亚语',
  'icelandic': '冰岛语',
  'estonian': '爱沙尼亚语',
  'latvian': '拉脱维亚语',
  'lithuanian': '立陶宛语',
  'albanian': '阿尔巴尼亚语',
  'serbian': '塞尔维亚语',
  'croatian': '克罗地亚语',
  'bosnian': '波斯尼亚语',
  'montenegrin': '黑山语',
  'macedonian': '马其顿语',
  'bulgarian': '保加利亚语',
  'slovenian': '斯洛文尼亚语',
  'slovak': '斯洛伐克语',
  'ukrainian': '乌克兰语',
  'belarusian': '白俄罗斯语',
  'kazakh': '哈萨克语',
  'uzbek': '乌兹别克语',
  'turkmen': '土库曼语',
  'kyrgyz': '吉尔吉斯语',
  'tajik': '塔吉克语',
  'mongolian': '蒙古语',
  'tibetan': '藏语',
  'uyghur': '维吾尔语',
  'zhuang': '壮语',
  'yi': '彝语',
  'miao': '苗语',
  'dong': '侗语',
  'tujia': '土家语',
  'bai': '白语',
  'hani': '哈尼语',
  'dai': '傣语',
  'lisu': '傈僳语',
  'va': '佤语',
  'lahu': '拉祜语',
  'achang': '阿昌语',
  'pumi': '普米语',
  'nu': '怒语',
  'derung': '独龙语',
  'bonan': '保安语',
  'yugur': '裕固语',
  'sarikoli': '塔吉克语',
  'tatar': '鞑靼语',
  'bashkir': '巴什基尔语',
  'chuvash': '楚瓦什语',
  'mari': '玛丽语',
  'mordvin': '莫德温语',
  'udmurt': '乌德穆尔特语',
  'komi': '科米语',
  'saami': '萨米语',
  'karelian': '卡累利阿语',
  'votic': '沃特语',
  'livonian': '利沃尼亚语',
  'sorbian': '索布语',
  'kashubian': '卡舒比语',
  'silesian': '西里西亚语',
  'aromanian': '阿罗马尼亚语',
  'friulian': '弗留利语',
  'ladin': '拉丁语',
  'romansh': '罗曼什语',
  'occitan': '奥克语',
  'provencal': '普罗旺斯语',
  'gascon': '加斯科尼语',
  'asturian': '阿斯图里亚斯语',
  'leonese': '莱昂语',
  'mirandese': '米兰德斯语',
  'aromanian': '阿罗马尼亚语',
  'istro romanian': '伊斯特罗罗马尼亚语',
  'megleno romanian': '梅格莱诺罗马尼亚语',
  'dalmatian': '达尔马提亚语',
  'istriot': '伊斯特里奥特语',
  'furlan': '弗留利语',
  'ladin': '拉丁语',
  'romansh': '罗曼什语',
  'friulian': '弗留利语',
  'sardinian': '撒丁语',
  'corsican': '科西嘉语',
  'sicilian': '西西里语',
  'neapolitan': '那不勒斯语',
  'calabrese': '卡拉布里亚语',
  'apulian': '普利亚语',
  'lucanian': '卢卡尼亚语',
  'campanian': '坎帕尼亚语',
  'molisan': '莫利塞语',
  'abruzzese': '阿布鲁佐语',
  'marchigiano': '马尔凯语',
  'umbrian': '翁布里亚语',
  'tuscan': '托斯卡纳语',
  'ligurian': '利古里亚语',
  'piedmontese': '皮埃蒙特语',
  'lombard': '伦巴第语',
  'emilian': '艾米利亚语',
  'romagnol': '罗马涅语',
  'venetian': '威尼斯语',
  'istrian': '伊斯特里亚语',
  'istriot': '伊斯特里奥特语',
  'dalmatian': '达尔马提亚语',
  'aromanian': '阿罗马尼亚语',
  'megleno romanian': '梅格莱诺罗马尼亚语',
  'istro romanian': '伊斯特罗罗马尼亚语',
};

function simpleTranslate(text: string): string {
  if (!text) return '';

  let result = text.toLowerCase();

  // 按长度排序，优先匹配长的短语
  const sortedKeys = Object.keys(translationDict).sort((a, b) => b.length - a.length);

  for (const key of sortedKeys) {
    const regex = new RegExp(`\\b${key}\\b`, 'gi');
    result = result.replace(regex, translationDict[key]);
  }

  return result;
}

export async function translateToChineseSimplified(text: string): Promise<string> {
  if (!text || text.length === 0) {
    return '';
  }

  try {
    // 尝试使用在线翻译
    const { translate } = await import('@vitalets/google-translate-api');
    const result = await translate(text, { to: 'zh-CN' });
    return result.text;
  } catch (error) {
    // 如果在线翻译失败，使用本地字典翻译
    console.warn(`⚠️  Online translation failed, using local dictionary`);
    return simpleTranslate(text);
  }
}

export async function translateArticles(articles: any[]): Promise<any[]> {
  console.log('🌐 Translating summaries to Chinese...');

  const translated = await Promise.all(
    articles.map(async (article) => {
      if (article.description) {
        article.description = await translateToChineseSimplified(article.description);
      }
      return article;
    })
  );

  console.log('✓ Translation completed\n');
  return translated;
}
